#!/bin/bash
# A simple script
if git cat-file -e master:CHANGELOG.md 2>/dev/null; then
	git checkout master -- CHANGELOG.md
fi
if git cat-file -e master:LICENSE.md 2>/dev/null; then
	git checkout master -- LICENSE.md
fi
if git cat-file -e master:README.md 2>/dev/null; then
	git checkout master -- README.md
fi
